const carConfigMaps = {
    auxheatwarnings: "intValue",
    averageSpeedReset: "doubleValue",
    averageSpeedStart: "doubleValue",
    decklidstatus: "boolValue",
    // departuretimesoc: "",
    // distanceElectricalReset: "",
    // distanceElectricalStart: "",
    // distanceGasReset: "",
    // distanceGasStart: "",
    distanceReset: "doubleValue",
    distanceStart: "doubleValue",
    // distanceZEReset: "",
    // distanceZEStart: "",
    doorLockStatusOverall: "intValue",
    doorStatusOverall: "intValue",
    doorlockstatusdecklid: "boolValue",
    doorlockstatusfrontleft: "boolValue",
    doorlockstatusfrontright: "boolValue",
    doorlockstatusgas: "boolValue",
    doorlockstatusrearleft: "boolValue",
    doorlockstatusrearright: "boolValue",
    doorlockstatusvehicle: "intValue",
    doorstatusfrontleft: "boolValue",
    doorstatusfrontright: "boolValue",
    doorstatusrearleft: "boolValue",
    doorstatusrearright: "boolValue",
    // drivenTimeReset: "",
    // drivenTimeStart: "",
    // drivenTimeZEReset: "",
    // drivenTimeZEStart: "",
    // ecoscoreaccel: "",
    // ecoscorebonusrange: "",
    // ecoscoreconst: "",
    // ecoscorefreewhl: "",
    // ecoscoretotal: "",
    // electricRatioOverall: "",
    // electricRatioReset: "",
    // electricRatioStart: "",
    // electricalRangeSkipIndication: "",
    // electricconsumptionreset: "",
    // electricconsumptionstart: "",
    // engineHoodStatus: "",
    // filterParticleLoading: "",
    // flipWindowStatus: "",
    // gasTankLevel: "",
    // gasTankLevelPercent: "",
    // gasTankRange: "",
    // gasconsumptionreset: "",
    // gasconsumptionstart: "",
    // hvBatteryThermalPropagationEvent: "",
    ignitionstate: "intValue",
    interiorProtectionSensorStatus: "intValue",
    // keylineActivationState: "",
    // languageHU: "",
    lastTheftWarning: "intValue",
    lastTheftWarningReason: "intValue",
    // liquidRangeSkipIndication: "",
    liquidconsumptionreset: "displayValue",
    liquidconsumptionstart: "displayValue",
    // maxrange: "",
    odo: "displayValue",
    oilLevel: "displayValue",
    oilWarningLevel: "intValue",
    overallRange: "displayValue",
    // parkEventLevel: "",
    parkEventType: "intValue",
    parkbrakestatus: "boolValue",
    positionHeading: "doubleValue",
    positionLat: "doubleValue",
    positionLong: "doubleValue",
    // proximityCalculationForVehiclePositionRequired: "",
    // rangeElectricWltp: "",
    // rangeelectric: "",
    rangeliquid: "displayValue",
    // rooftopstatus: "",
    // serviceintervaldays: "",
    serviceintervaldistance: "displayValue",
    // soc: "",
    speedAlertConf: "speedAlertConfigurationValue",
    speedUnitFromIC: "speedDistanceUnit",
    starterBatteryState: "intValue",
    // sunroofEvent: "",
    // sunroofEventActive: "",
    // sunroofStatusFrontBlind: "",
    // sunroofStatusRearBlind: "",
    // sunroofstatus: "",
    tankLevelAdBlue: "displayValue",
    tanklevelpercent: "displayValue",
    // tcuConnectionStateLowChannel: "",
    // temperatureUnitHU: "",
    theftAlarmActive: "boolValue",
    theftSystemArmed: "boolValue",
    // timeFormatHU: "",
    // tireMarkerFrontLeft: "",
    // tireMarkerFrontRight: "",
    // tireMarkerRearLeft: "",
    // tireMarkerRearRight: "",
    // tirePressMeasTimestamp: "",
    // tireSensorAvailable: "",
    // tireWarningLevelPrw: "",
    // tiremarker: "",
    tirepressureFrontLeft: "displayValue",
    tirepressureFrontRight: "displayValue",
    tirepressureRearLeft: "displayValue",
    tirepressureRearRight: "displayValue",
    tirewarninglamp: "boolValue",
    tirewarningsprw: "boolValue",
    tirewarningsrdk: "boolValue",
    towProtectionSensorStatus: "intValue",
    // trackingStateHU: "",
    vehicleDataConnectionState: "boolValue",
    // vehicleHealthStatus: "",
    vehicleLockState: "intValue",
    // vehiclePositionErrorCode: "",
    // vtime: "",
    warningbrakefluid: "boolValue",
    warningbrakeliningwear: "boolValue",
    warningcoolantlevellow: "boolValue",
    warningenginelight: "boolValue",
    // warningwashwater: "stringValue",
    windowStatusOverall: "intValue",
    // windowStatusRearBlind: "intValue",
    // windowStatusRearLeftBlind: "intValue",
    // windowStatusRearRightBlind: "intValue",
    windowstatusfrontleft: "intValue",
    windowstatusfrontright: "intValue",
    windowstatusrearleft: "intValue",
    windowstatusrearright: "intValue"
};


const commandToCarParameterMap = {
    DoorsLock: "vehicleLockState",
    DoorsUnlock: "vehicleLockState",
    TheftalarmDeselectInterior: "serviceintervaldistance",
    TheftalarmDeselectTow: "towProtectionSensorStatus", 
    TheftalarmSelectTow: "towProtectionSensorStatus",
    TheftalarmSelectInterior: "serviceintervaldistance",
    TheftalarmStop: "theftAlarmActive",
    WindowsClose: "windowStatusOverall",
    WindowsOpen: "windowStatusOverall",
    WindowsVentilate: "windowStatusOverall"
};

module.exports = {
    carConfigMaps,
    commandToCarParameterMap
};